export const AGE_GROUPS: string[] = ["14-17", "18-21", "22-25"];

export const EMOTIONS: { key: string; en: string }[] = [
  { key: "amazed", en: "Amazed" },
  { key: "amused", en: "Amused" },
  { key: "angry", en: "Angry" },
  { key: "annoyed", en: "Annoyed" },
  { key: "anxious", en: "Anxious" },
  { key: "ashamed", en: "Ashamed" },
  { key: "brave", en: "Brave" },
  { key: "calm", en: "Calm" },
  { key: "confident", en: "Confident" },
  { key: "content", en: "Content" },
  { key: "disappointed", en: "Disappointed" },
  { key: "discouraged", en: "Discouraged" },
  { key: "disgusted", en: "Disgusted" },
  { key: "drained", en: "Drained" },
  { key: "embarrassed", en: "Embarrassed" },
  { key: "excited", en: "Excited" },
  { key: "frustrated", en: "Frustrated" },
  { key: "grateful", en: "Grateful" },
  { key: "guilty", en: "Guilty" },
  { key: "happy", en: "Happy" },
  { key: "hopeful", en: "Hopeful" },
  { key: "hopeless", en: "Hopeless" },
  { key: "indifferent", en: "Indifferent" },
  { key: "irritated", en: "Irritated" },
  { key: "jealous", en: "Jealous" },
  { key: "passionate", en: "Passionate" },
  { key: "proud", en: "Proud" },
  { key: "relieved", en: "Relieved" },
  { key: "sad", en: "Sad" },
  { key: "satisfied", en: "Satisfied" },
];

export const EMOTION_CATEGORIES: { [key: string]: { titleKey: string; emotions: string[], mood: 'positive' | 'negative' } } = {
  uplifting: {
    titleKey: 'emotionCategoryUplifting',
    emotions: [
      'amazed', 'amused', 'brave', 'calm', 'confident', 'content', 'excited',
      'grateful', 'happy', 'hopeful', 'passionate', 'proud', 'relieved', 'satisfied'
    ],
    mood: 'positive',
  },
  heavy: {
    titleKey: 'emotionCategoryHeavy',
    emotions: [
      'angry', 'anxious', 'ashamed', 'disappointed', 'discouraged', 'disgusted',
      'drained', 'embarrassed', 'frustrated', 'guilty', 'hopeless', 'sad'
    ],
    mood: 'negative',
  },
  turbulent: {
    titleKey: 'emotionCategoryTurbulent',
    emotions: ['annoyed', 'indifferent', 'irritated', 'jealous'],
    mood: 'negative',
  }
};

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी' }, // Hindi
  { code: 'bn', name: 'বাংলা' }, // Bengali
  { code: 'mr', name: 'मराठी' }, // Marathi
  { code: 'te', name: 'తెలుగు' }, // Telugu
  { code: 'ta', name: 'தமிழ்' }, // Tamil
  { code: 'gu', name: 'ગુજરાતી' }, // Gujarati
  { code: 'ur', name: 'اردو' }, // Urdu
  { code: 'kn', name: 'ಕನ್ನಡ' }, // Kannada
  { code: 'or', name: 'ଓଡ଼ିଆ' }, // Odia
  { code: 'ml', name: 'മലയാളം' }, // Malayalam
  { code: 'pa', name: 'ਪੰਜਾਬੀ' }, // Punjabi
];

export const TRANSLATIONS: { [key: string]: { [key: string]: any } } = {
  en: {
    welcome: 'Welcome to {appName}',
    appName: 'Sankalp',
    description: 'Your private space to understand and track emotions — safe, simple, supportive.',
    ageLabel: 'First, which age group are you in?',
    ageExplainer: 'We ask this to tailor language and advice for your age group.',
    emotionLabel: 'What feelings are present for you now?',
    emotionCategoryUplifting: 'Uplifting',
    emotionCategoryHeavy: 'Heavy',
    emotionCategoryTurbulent: 'Turbulent',
    intensityLabel: 'How strong are these feelings?',
    startButton: 'Start a Conversation',
    chatPlaceholder: 'Type or speak your message here...',
    dashboardTitle: 'Your Wellness Dashboard',
    currentStreak: 'Current Streak',
    challengesDone: 'Challenges Done',
    dailyChallenge: 'Daily Challenge',
    weeklyMoodTrend: 'Weekly Mood Trend',
    emotionBreakdown: 'Emotion Breakdown',
    streakProgress: 'Streak Progress',
    weeklyChallenge: 'Weekly Challenge',
    markAsComplete: 'Mark as Complete',
    completed: 'Completed!',
    goalMet: 'Goal Met!',
    trackADay: 'Track a Day',
    days: 'days',
    aiCallWelcomeMessage: "Hello! I am Sankalp, your personal AI assistant. You can start a conversation by telling me how you feel.",
    emotions: {
      amazed: "Amazed", amused: "Amused", angry: "Angry", annoyed: "Annoyed", anxious: "Anxious", ashamed: "Ashamed", brave: "Brave", calm: "Calm", confident: "Confident", content: "Content", disappointed: "Disappointed", discouraged: "Discouraged", disgusted: "Disgusted", drained: "Drained", embarrassed: "Embarrassed", excited: "Excited", frustrated: "Frustrated", grateful: "Grateful", guilty: "Guilty", happy: "Happy", hopeful: "Hopeful", hopeless: "Hopeless", indifferent: "Indifferent", irritated: "Irritated", jealous: "Jealous", passionate: "Passionate", proud: "Proud", relieved: "Relieved", sad: "Sad", satisfied: "Satisfied",
    }
  },
  hi: {
    welcome: '{appName} में आपका स्वागत है',
    appName: 'संकल्प',
    description: 'भावनाओं को समझने और ट्रैक करने के लिए आपकी निजी जगह — सुरक्षित, सरल, सहायक।',
    ageLabel: 'सबसे पहले, आप किस आयु वर्ग में हैं?',
    ageExplainer: 'हम यह आपकी आयु के अनुसार भाषा और सलाह को अनुकूलित करने के लिए पूछते हैं।',
    emotionLabel: 'अभी आपके मन में कौन सी भावनाएँ मौजूद हैं?',
    emotionCategoryUplifting: 'उत्साहजनक',
    emotionCategoryHeavy: 'भारी',
    emotionCategoryTurbulent: 'अशांत',
    intensityLabel: 'ये भावनाएँ कितनी तीव्र हैं?',
    startButton: 'बातचीत शुरू करें',
    chatPlaceholder: 'अपना संदेश यहाँ टाइप करें या बोलें...',
    dashboardTitle: 'आपका कल्याण डैशबोर्ड',
    currentStreak: 'वर्तमान स्ट्रीक',
    challengesDone: 'पूरी हुई चुनौतियाँ',
    dailyChallenge: 'दैनिक चुनौती',
    weeklyMoodTrend: 'साप्ताहिक मूड ट्रेंड',
    emotionBreakdown: 'भावनाओं का विश्लेषण',
    streakProgress: 'स्ट्रीक प्रगति',
    weeklyChallenge: 'साप्ताहिक चुनौती',
    markAsComplete: 'पूर्ण के रूप में चिह्नित करें',
    completed: 'पूर्ण!',
    goalMet: 'लक्ष्य पूरा हुआ!',
    trackADay: 'एक दिन ट्रैक करें',
    days: 'दिन',
    aiCallWelcomeMessage: "नमस्ते! मैं संकल्प हूँ, आपका व्यक्तिगत AI सहायक। आप कैसा महसूस कर रहे हैं, यह बताकर बातचीत शुरू कर सकते हैं।",
    emotions: {
      amazed: "आश्चर्यचकित", amused: "प्रसन्न", angry: "क्रोधित", annoyed: "चिढ़ा हुआ", anxious: "चिंतित", ashamed: "शर्मिंदा", brave: "बहादुर", calm: "शांत", confident: "आत्मविश्वासी", content: "संतुष्ट", disappointed: "निराश", discouraged: "हतोत्साहित", disgusted: "घृणित", drained: "थका हुआ", embarrassed: "शर्मिंदा", excited: "उत्साहित", frustrated: "कुंठित", grateful: "आभारी", guilty: "दोषी", happy: "खुश", hopeful: "आशावान", hopeless: "निराश", indifferent: "उदासीन", irritated: "चिड़चिड़ा", jealous: "ईर्ष्यालु", passionate: "भावुक", proud: "गौरवान्वित", relieved: "राहत मिली", sad: "दुखी", satisfied: "संतुष्ट",
    }
  },
  bn: {
    welcome: '{appName}ে স্বাগতম',
    appName: 'সংকল্প',
    description: 'আপনার অনুভূতি বোঝার এবং ট্র্যাক করার জন্য আপনার ব্যক্তিগত স্থান — নিরাপদ, সহজ, সহায়ক।',
    ageLabel: 'প্রথমত, আপনি কোন বয়স গোষ্ঠীর মধ্যে পড়েন?',
    ageExplainer: 'আপনার বয়স গোষ্ঠীর জন্য ভাষা এবং পরামর্শ তৈরি করার জন্য আমরা এটি জিজ্ঞাসা করি।',
    emotionLabel: 'এই মুহূর্তে আপনার মধ্যে কোন অনুভূতি উপস্থিত আছে?',
    emotionCategoryUplifting: 'উৎসাহব্যঞ্জক',
    emotionCategoryHeavy: 'ভারী',
    emotionCategoryTurbulent: 'অশান্ত',
    intensityLabel: 'এই অনুভূতিগুলো কতটা তীব্র?',
    startButton: 'কথোপকথন শুরু করুন',
    chatPlaceholder: 'আপনার বার্তা এখানে টাইপ করুন বা বলুন...',
    dashboardTitle: 'আপনার সুস্থতা ড্যাশবোর্ড',
    currentStreak: 'বর্তমান স্ট্রিক',
    challengesDone: 'চ্যালেঞ্জ সম্পন্ন হয়েছে',
    dailyChallenge: 'দৈনিক চ্যালেঞ্জ',
    weeklyMoodTrend: 'সাপ্তাহিক মুড ট্রেন্ড',
    emotionBreakdown: 'অনুভূতির ভাঙ্গন',
    streakProgress: 'স্ট্রিক অগ্রগতি',
    weeklyChallenge: 'সাপ্তাহিক চ্যালেঞ্জ',
    markAsComplete: 'সম্পন্ন হিসাবে চিহ্নিত করুন',
    completed: 'সম্পন্ন!',
    goalMet: 'লক্ষ্য পূরণ!',
    trackADay: 'একটি দিন ট্র্যাক করুন',
    days: 'দিন',
    aiCallWelcomeMessage: "হ্যালো! আমি সংকল্প, আপনার ব্যক্তিগত এআই সহকারী। আপনি কেমন অনুভব করছেন তা বলে কথোপকথন শুরু করতে পারেন।",
    emotions: {
      amazed: " বিস্মিত", amused: "আনন্দিত", angry: "রাগান্বিত", annoyed: "বিরক্ত", anxious: "উদ্বিগ্ন", ashamed: "লজ্জিত", brave: "সাহসী", calm: "শান্ত", confident: "আত্মবিশ্বাসী", content: "সন্তুষ্ট", disappointed: "হতাশ", discouraged: "নিরুৎসাহিত", disgusted: "বিরক্ত", drained: "ক্লান্ত", embarrassed: "অস্বস্তিতে", excited: "উত্তেজিত", frustrated: "হতাশ", grateful: "কৃতজ্ঞ", guilty: "দোষী", happy: "সুখী", hopeful: "আশাবাদী", hopeless: "হতাশ", indifferent: "উদাসীন", irritated: "জ্বালাতন", jealous: "ঈর্ষান্বিত", passionate: "আবেগপ্রবণ", proud: "গর্বিত", relieved: "স্বস্তি", sad: "দুঃখিত", satisfied: "সন্তুষ্ট",
    }
  },
  mr: {
    welcome: '{appName}मध्ये आपले स्वागत आहे',
    appName: 'संकल्प',
    description: 'तुमच्या भावना समजून घेण्यासाठी आणि त्यांचा मागोवा घेण्यासाठी तुमची खाजगी जागा — सुरक्षित, सोपी, সহায়क.',
    ageLabel: 'प्रथम, तुम्ही कोणत्या वयोगटात आहात?',
    ageExplainer: 'तुमच्या वयोगटासाठी भाषा आणि सल्ला तयार करण्यासाठी आम्ही हे विचारतो.',
    emotionLabel: 'सध्या तुमच्या मनात कोणत्या भावना आहेत?',
    emotionCategoryUplifting: 'उत्साहवर्धक',
    emotionCategoryHeavy: 'जड',
    emotionCategoryTurbulent: 'अशांत',
    intensityLabel: 'या भावना किती तीव्र आहेत?',
    startButton: 'संभाषण सुरू करा',
    chatPlaceholder: 'तुमचा संदेश येथे टाइप करा किंवा बोला...',
    dashboardTitle: 'तुमचा वेलनेस डॅशबोर्ड',
    currentStreak: 'सध्याची स्ट्रीक',
    challengesDone: 'पूर्ण झालेली आव्हाने',
    dailyChallenge: 'दैनिक आव्हान',
    weeklyMoodTrend: 'साप्ताहिक मूड ट्रेंड',
    emotionBreakdown: 'भावनांचे विश्लेषण',
    streakProgress: 'स्ट्रीकची प्रगती',
    weeklyChallenge: 'साप्ताहिक आव्हान',
    markAsComplete: 'पूर्ण म्हणून चिन्हांकित करा',
    completed: 'पूर्ण झाले!',
    goalMet: 'ध्येय गाठले!',
    trackADay: 'एक दिवस ट्रॅक करा',
    days: 'दिवस',
    aiCallWelcomeMessage: "नमस्कार! मी संकल्प आहे, तुमचा वैयक्तिक AI सहाय्यक. तुम्हाला कसे वाटते हे सांगून तुम्ही संभाषण सुरू करू शकता.",
    emotions: {
      amazed: "आश्चर्यचकित", amused: "आनंदित", angry: "रागावलेला", annoyed: "चिडलेला", anxious: "चिंतित", ashamed: "लाजिरवाणा", brave: "शूर", calm: "शांत", confident: "आत्मविश्वासी", content: "समाधानी", disappointed: "निराश", discouraged: "निరుत्साहित", disgusted: "तिरस्कार", drained: "थकलेला", embarrassed: "लज्जित", excited: "उत्तेजित", frustrated: "निराश", grateful: "कृतज्ञ", guilty: "दोषी", happy: "आनंदी", hopeful: "आशावादी", hopeless: "निराश", indifferent: "उदासीन", irritated: "चिडचिडलेला", jealous: "मत्सरी", passionate: "उत्साही", proud: "अभिमानी", relieved: "निःश्वास", sad: "दुःखी", satisfied: "समाधानी",
    }
  },
  te: {
    welcome: '{appName}ానికి స్వాగతం',
    appName: 'సంకల్ప',
    description: 'భావోద్వేగాలను అర్థం చేసుకోవడానికి మరియు ట్రాక్ చేయడానికి మీ ప్రైవేట్ స్థలం — సురక్షితమైనది, సరళమైనది, సహాయకారి.',
    ageLabel: 'మొదట, మీరు ఏ వయస్సు వర్గానికి చెందినవారు?',
    ageExplainer: 'మీ వయస్సు వర్గానికి తగిన భాష మరియు సలహాలను అందించడానికి మేము ఇది అడుగుతున్నాము.',
    emotionLabel: 'ప్రస్తుతం మీలో ఏ భావాలు ఉన్నాయి?',
    emotionCategoryUplifting: 'ఉత్తేజకరమైన',
    emotionCategoryHeavy: 'భారీ',
    emotionCategoryTurbulent: 'అశాంత',
    intensityLabel: 'ఈ భావాలు ఎంత బలంగా ఉన్నాయి?',
    startButton: 'సంభాషణ ప్రారంభించండి',
    chatPlaceholder: 'మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి లేదా మాట్లాడండి...',
    dashboardTitle: 'మీ వెల్నెస్ డాష్‌బోర్డ్',
    currentStreak: 'ప్రస్తుత స్ట్రీక్',
    challengesDone: 'పూర్తయిన సవాళ్లు',
    dailyChallenge: 'రోజువారీ సవాలు',
    weeklyMoodTrend: 'వారపు మూడ్ ట్రెండ్',
    emotionBreakdown: 'భావోద్వేగ విశ్లేషణ',
    streakProgress: 'స్ట్రీక్ పురోగతి',
    weeklyChallenge: 'వారపు సవాలు',
    markAsComplete: 'పూర్తయినట్లుగా గుర్తించండి',
    completed: 'పూర్తయింది!',
    goalMet: 'లక్ష్యం పూర్తయింది!',
    trackADay: 'ఒక రోజు ట్రాక్ చేయండి',
    days: 'రోజులు',
    aiCallWelcomeMessage: "హలో! నేను సంకల్ప్, మీ వ్యక్తిగత AI సహాయకుడు. మీరు ఎలా భావిస్తున్నారో చెప్పడం ద్వారా సంభాషణను ప్రారంభించవచ్చు.",
    emotions: {
      amazed: "ఆశ్చర్యపడ్డాను", amused: "వినోదం", angry: "కోపంగా", annoyed: "విసుగు", anxious: "ఆందోళనగా", ashamed: "సిగ్గుపడు", brave: "ధైర్యంగా", calm: "ప్రశాంతంగా", confident: "నమ్మకంగా", content: "సంతృప్తి", disappointed: "నిరాశ", discouraged: "నిరుత్సాహం", disgusted: "అసహ్యం", drained: "అలసిపోయాను", embarrassed: "ఇబ్బందిగా", excited: "ఉత్సాహంగా", frustrated: "నిరాశ", grateful: "కృతజ్ఞతతో", guilty: "అపరాధి", happy: "సంతోషంగా", hopeful: "ఆశాజనకంగా", hopeless: "నిరాశ", indifferent: "ఉదాసీనంగా", irritated: "చిరాకుగా", jealous: "ఈర్ష్యగా", passionate: "ఉద్రేకంతో", proud: "గర్వంగా", relieved: "ఉపశమనం", sad: "విచారంగా", satisfied: "సంతృప్తిగా",
    }
  },
  ta: {
    welcome: '{appName}த்திற்கு வரவேற்கிறோம்',
    appName: 'சங்கல்ப',
    description: 'உணர்வுகளைப் புரிந்துகொள்ளவும் கண்காணிக்கவும் உங்கள் தனிப்பட்ட இடம் — பாதுகாப்பானது, எளிமையானது, ஆதரவானது.',
    ageLabel: 'முதலில், நீங்கள் எந்த வயதுக் குழுவில் இருக்கிறீர்கள்?',
    ageExplainer: 'உங்கள் வயதினருக்கேற்ப மொழி மற்றும் ஆலோசனையை வழங்குவதற்காக இதைக் கேட்கிறோம்.',
    emotionLabel: 'தற்போது உங்களுக்கு என்ன உணர்வுகள் உள்ளன?',
    emotionCategoryUplifting: 'ஊக்கமளிக்கும்',
    emotionCategoryHeavy: 'கனமான',
    emotionCategoryTurbulent: 'கொந்தளிப்பான',
    intensityLabel: 'இந்த உணர்வுகள் எவ்வளவு வலுவாக உள்ளன?',
    startButton: 'உரையாடலைத் தொடங்குங்கள்',
    chatPlaceholder: 'உங்கள் செய்தியை இங்கே தட்டச்சு செய்யவும் அல்லது பேசவும்...',
    dashboardTitle: 'உங்கள் நலவாழ்வு டாஷ்போர்டு',
    currentStreak: 'தற்போதைய தொடர்',
    challengesDone: 'முடிக்கப்பட்ட சவால்கள்',
    dailyChallenge: 'தினசரி சவால்',
    weeklyMoodTrend: 'வாராந்திர மனநிலை போக்கு',
    emotionBreakdown: 'உணர்ச்சிப் பகுப்பாய்வு',
    streakProgress: 'தொடர் முன்னேற்றம்',
    weeklyChallenge: 'வாராந்திர சவால்',
    markAsComplete: 'முடிந்தது எனக் குறிக்கவும்',
    completed: 'முடிந்தது!',
    goalMet: 'இலக்கு எட்டப்பட்டது!',
    trackADay: 'ஒரு நாளைக் கண்காணிக்கவும்',
    days: 'நாட்கள்',
    aiCallWelcomeMessage: "வணக்கம்! நான் சங்கல்ப், உங்கள் தனிப்பட்ட AI உதவியாளர். நீங்கள் எப்படி உணர்கிறீர்கள் என்று சொல்லி உரையாடலைத் தொடங்கலாம்.",
    emotions: {
      amazed: "வியப்பு", amused: "மகிழ்ச்சி", angry: "கோபம்", annoyed: "எரிச்சல்", anxious: "கவலை", ashamed: "வெட்கம்", brave: "தைரியம்", calm: "அமைதி", confident: "தன்னம்பிக்கை", content: "திருப்தி", disappointed: "ஏமாற்றம்", discouraged: "மனமுடைந்த", disgusted: "அருவருப்பு", drained: "சோர்வு", embarrassed: " சங்கடம்", excited: "உற்சாகம்", frustrated: "விரக்தி", grateful: "நன்றியுடன்", guilty: "குற்ற உணர்ச்சி", happy: "மகிழ்ச்சி", hopeful: "நம்பிக்கை", hopeless: "நம்பிக்கையற்ற", indifferent: "उदासीन", irritated: "எரிச்சல்", jealous: "பொறாமை", passionate: "உணர்ச்சிவசப்பட்ட", proud: "பெருமை", relieved: "நிம்மதி", sad: "சோகம்", satisfied: "திருப்தி",
    }
  },
  gu: {
    welcome: '{appName}માં આપનું સ્વાગત છે',
    appName: 'સંકલ્પ',
    description: 'લાગણીઓને સમજવા અને ટ્રૅક કરવા માટે તમારી ખાનગી જગ્યા — સલામત, સરળ, સહાયક।',
    ageLabel: 'પહેલા, તમે કયા વય જૂથમાં છો?',
    ageExplainer: 'અમે આ તમારી વય જૂથ માટે ભાષા અને સલાહને અનુરૂપ બનાવવા માટે પૂછીએ છીએ।',
    emotionLabel: 'અત્યારે તમારામાં કઈ લાગણીઓ હાજર છે?',
    emotionCategoryUplifting: 'પ્રોત્સાહક',
    emotionCategoryHeavy: 'ભારે',
    emotionCategoryTurbulent: 'અશાંત',
    intensityLabel: 'આ લાગણીઓ કેટલી તીવ્ર છે?',
    startButton: 'વાતચીત શરૂ કરો',
    chatPlaceholder: 'તમારો સંદેશ અહીં ટાઇપ કરો અથવા બોલો...',
    dashboardTitle: 'તમારું વેલનેસ ડેશબોર્ડ',
    currentStreak: 'વર્તમાન સ્ટ્રીક',
    challengesDone: 'પૂર્ણ થયેલ પડકારો',
    dailyChallenge: 'દૈનિક પડકાર',
    weeklyMoodTrend: 'સાપ્તાહિક મૂડ ટ્રેન્ડ',
    emotionBreakdown: 'લાગણીઓનું વિશ્લેષણ',
    streakProgress: 'સ્ટ્રીક પ્રગતિ',
    weeklyChallenge: 'સાપ્તાહિક પડકાર',
    markAsComplete: 'પૂર્ણ તરીકે ચિહ્નિત કરો',
    completed: 'પૂર્ણ!',
    goalMet: 'લક્ષ્ય પ્રાપ્ત થયું!',
    trackADay: 'એક દિવસ ટ્રૅક કરો',
    days: 'દિવસો',
    aiCallWelcomeMessage: "નમસ્તે! હું સંકલ્પ છું, તમારો અંગત AI સહાયક. તમે કેવું અનુભવો છો તે જણાવીને વાતચીત શરૂ કરી શકો છો.",
    emotions: {
      amazed: "આશ્ચર્યચકિત", amused: "ખુશ", angry: "ગુસ્સે", annoyed: "ચીડાયેલું", anxious: "ચિંતિત", ashamed: "શરમ", brave: "બહાદુર", calm: "શાંત", confident: "આત્મવિશ્વાસુ", content: "સંતુષ્ટ", disappointed: "નિરાશ", discouraged: "નિરાશ", disgusted: "અણગમો", drained: "થાકેલું", embarrassed: "શરમ", excited: "ઉત્સાહિત", frustrated: "નિરાશ", grateful: "આભારી", guilty: "દોષિત", happy: "ખુશ", hopeful: "આશાવાદી", hopeless: "નિરાશ", indifferent: "ઉદાસીન", irritated: "ચીડ", jealous: "ઈર્ષ્યા", passionate: "ઉત્સાહી", proud: "ગર્વ", relieved: "રાહત", sad: "દુઃખી", satisfied: "સંતુષ્ટ",
    }
  },
  ur: {
    welcome: '{appName} میں خوش آمدید',
    appName: 'سنکلپ',
    description: 'جذبات کو سمجھنے اور ٹریک کرنے کے لیے آپ کی نجی جگہ — محفوظ، سادہ، معاون۔',
    ageLabel: 'سب سے پہلے، آپ کس عمر کے گروپ میں ہیں؟',
    ageExplainer: 'ہم یہ آپ کے عمر کے گروپ کے لیے زبان اور مشورے کو تیار کرنے کے لیے پوچھتے ہیں۔',
    emotionLabel: 'اس وقت آپ کے اندر کون سے احساسات موجود ہیں؟',
    emotionCategoryUplifting: 'حوصلہ افزا',
    emotionCategoryHeavy: 'بھاری',
    emotionCategoryTurbulent: 'پُرتلاطم',
    intensityLabel: 'یہ احساسات کتنے شدید ہیں؟',
    startButton: 'گفتگو شروع کریں',
    chatPlaceholder: 'اپنا پیغام یہاں ٹائپ کریں یا بولیں...',
    dashboardTitle: 'آپ کا ویلنس ڈیش بورڈ',
    currentStreak: 'موجودہ اسٹریک',
    challengesDone: 'مکمل شدہ چیلنجز',
    dailyChallenge: 'روزانہ کا چیلنج',
    weeklyMoodTrend: 'ہفتہ وار موڈ کا رجحان',
    emotionBreakdown: 'جذبات کا تجزیہ',
    streakProgress: 'اسٹریک کی پیشرفت',
    weeklyChallenge: 'ہفتہ وار چیلنج',
    markAsComplete: 'مکمل کے بطور نشان زد کریں',
    completed: 'مکمل!',
    goalMet: 'ہدف پورا ہو گیا!',
    trackADay: 'ایک دن ٹریک کریں',
    days: 'دن',
    aiCallWelcomeMessage: "ہیلو! میں سنکلپ ہوں، آپ کا ذاتی AI اسسٹنٹ۔ آپ کیسا محسوس کر رہے ہیں یہ بتا کر بات چیت شروع کر سکتے ہیں۔",
    emotions: {
      amazed: "حیران", amused: "خوش", angry: "ناراض", annoyed: "چڑچڑا", anxious: "پریشان", ashamed: "شرمندہ", brave: "بہادر", calm: "پرسکون", confident: "پراعتماد", content: "مطمئن", disappointed: "مایوس", discouraged: "حوصلہ شکنی", disgusted: "نفرت", drained: "تھکا ہوا", embarrassed: "شرمندہ", excited: "پرجوش", frustrated: "مایوس", grateful: "شکر گزار", guilty: "قصوروار", happy: "خوش", hopeful: "پُرامید", hopeless: "ناامید", indifferent: "لاتعلق", irritated: "چڑچড়া", jealous: "حاسد", passionate: "پرجوش", proud: "فخر", relieved: "سکون", sad: "اداس", satisfied: "مطمئن",
    }
  },
  kn: {
    welcome: '{appName}ಕ್ಕೆ ಸ್ವಾಗತ',
    appName: 'ಸಂಕಲ್ಪ',
    description: 'ಭಾವನೆಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಖಾಸಗಿ ಸ್ಥಳ — ಸುರಕ್ಷಿತ, ಸರಳ, ಸಹಾಯಕ.',
    ageLabel: 'ಮೊದಲಿಗೆ, ನೀವು ಯಾವ ವಯಸ್ಸಿನ ಗುಂಪಿನಲ್ಲಿದ್ದೀರಿ?',
    ageExplainer: 'ನಿಮ್ಮ ವಯಸ್ಸಿನ ಗುಂಪಿಗೆ ಭಾಷೆ ಮತ್ತು ಸಲಹೆಯನ್ನು ಹೊಂದಿಸಲು ನಾವು ಇದನ್ನು ಕೇಳುತ್ತೇವೆ.',
    emotionLabel: 'ಈಗ ನಿಮ್ಮಲ್ಲಿ ಯಾವ ಭಾವನೆಗಳಿವೆ?',
    emotionCategoryUplifting: 'ಉತ್ತೇಜಕ',
    emotionCategoryHeavy: 'ಭಾರವಾದ',
    emotionCategoryTurbulent: 'ಪ್ರಕ್ಷುಬ್ಧ',
    intensityLabel: 'ಈ ಭಾವನೆಗಳು ಎಷ್ಟು ಪ್ರಬಲವಾಗಿವೆ?',
    startButton: 'ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    chatPlaceholder: 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮಾತನಾಡಿ...',
    dashboardTitle: 'ನಿಮ್ಮ ಸ್ವಾಸ್ಥ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    currentStreak: 'ಪ್ರಸ್ತುತ ಸ್ಟ್ರೀಕ್',
    challengesDone: 'ಪೂರ್ಣಗೊಂಡ ಸವಾಲುಗಳು',
    dailyChallenge: 'ದೈನಂದಿನ ಸವಾಲು',
    weeklyMoodTrend: 'ವಾರದ ಮನಸ್ಥಿತಿ ಟ್ರೆಂಡ್',
    emotionBreakdown: 'ಭಾವನೆಗಳ ವಿಶ್ಲೇಷಣೆ',
    streakProgress: 'ಸ್ಟ್ರೀಕ್ ಪ್ರಗತಿ',
    weeklyChallenge: 'ವಾರದ ಸವಾಲು',
    markAsComplete: 'ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    completed: 'ಪೂರ್ಣಗೊಂಡಿದೆ!',
    goalMet: 'ಗುರಿ ತಲುಪಿದೆ!',
    trackADay: 'ಒಂದು ದಿನವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    days: 'ದಿನಗಳು',
    aiCallWelcomeMessage: "ಹಲೋ! ನಾನು ಸಂಕಲ್ಪ, ನಿಮ್ಮ ವೈಯಕ್ತಿಕ AI ಸಹಾಯಕ. ನೀವು ಹೇಗೆ ಭಾವಿಸುತ್ತಿದ್ದೀರಿ ಎಂದು ಹೇಳುವ ಮೂಲಕ ಸಂಭಾಷಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಬಹುದು.",
    emotions: {
      amazed: "ಆಶ್ಚರ್ಯಚಕಿತ", amused: "ಸಂತೋಷಗೊಂಡ", angry: "ಕೋపಗೊಂಡ", annoyed: "ಕಿರಿಕಿರಿಗೊಂಡ", anxious: "ಆತಂಕಿತ", ashamed: "ನಾಚಿಕೆಗೊಳಗಾದ", brave: "ಧೈರ್ಯಶಾಲಿ", calm: "ಶಾಂತ", confident: "ಆತ್ಮವಿಶ್ವಾಸಿ", content: "ತೃಪ್ತ", disappointed: "ನಿರಾಶೆಗೊಂಡ", discouraged: "ನಿರುತ್ಸಾಹಗೊಂಡ", disgusted: "ಅಸಹ್ಯಗೊಂಡ", drained: "ದಣಿದ", embarrassed: "ಮುಜುಗರಗೊಂಡ", excited: "ಉತ್ತేజಿತ", frustrated: "ಹತಾಶೆಗೊಂಡ", grateful: "ಕೃತಜ್ಞ", guilty: "ಅಪರಾಧಿ", happy: "ಸಂತೋಷ", hopeful: "ಆಶಾವಾದಿ", hopeless: "ನಿರಾಶೆ", indifferent: "ਉਦਾਸੀਨ", irritated: "ಕಿರಿಕಿರಿಗೊಂಡ", jealous: "ಅಸೂಯೆ ಪಟ್ಟ", passionate: "ಭಾವೋದ್ರಿಕ್ತ", proud: "ಹೆಮ್ಮೆ", relieved: "நிம்மதி", sad: "ದುಃಖಿತ", satisfied: "ತೃಪ್ತ",
    }
  },
  or: {
    welcome: '{appName}କୁ ସ୍ୱାଗତ',
    appName: 'ସଂକଳ୍ପ',
    description: 'ଭାବନାକୁ ବୁଝିବା ଏବଂ ଟ୍ରାକ୍ କରିବା ପାଇଁ ଆପଣଙ୍କର ବ୍ୟକ୍ତିଗତ ସ୍ଥାନ — ସୁରକ୍ଷିତ, ସରଳ, ସହାୟକ।',
    ageLabel: 'ପ୍ରଥମେ, ଆପଣ କେଉଁ ବୟସ ବର୍ଗରେ ଅଛନ୍ତି?',
    ageExplainer: 'ଆମେ ଏହା ଆପଣଙ୍କ ବୟସ ବର୍ଗ ପାଇଁ ଭାଷା ଏବଂ ପରାମର୍ଶକୁ ଅନୁକୂଳ କରିବା ପାଇଁ ପଚାରୁ।',
    emotionLabel: 'ବର୍ତ୍ତମାନ ଆପଣଙ୍କ ମନରେ କେଉଁ ଭାବନା ଅଛି?',
    emotionCategoryUplifting: 'ଉତ୍ସାହଜନକ',
    emotionCategoryHeavy: 'ଭାରୀ',
    emotionCategoryTurbulent: 'ଅଶାନ୍ତ',
    intensityLabel: 'ଏହି ଭାବନାଗୁଡ଼ିକ କେତେ ଶକ୍ତିଶାଳୀ?',
    startButton: 'ଆଳାପ ଆରମ୍ଭ କରନ୍ତୁ',
    chatPlaceholder: 'ଆପଣଙ୍କ ସନ୍ଦେଶ ଏଠାରେ ଟାଇପ୍ କରନ୍ତୁ କିମ୍ବା କୁହନ୍ତୁ...',
    dashboardTitle: 'ଆପଣଙ୍କ ସୁସ୍ଥତା ଡ୍ୟାସବୋର୍ଡ',
    currentStreak: 'ସାମ୍ପ୍ରତିକ ଷ୍ଟ୍ରିକ୍',
    challengesDone: 'ଚ୍ୟାଲେଞ୍ଜ ସମାପ୍ତ',
    dailyChallenge: 'ଦୈନିକ ଚ୍ୟାଲେଞ୍ଜ',
    weeklyMoodTrend: 'ସାପ୍ତାହିକ ମୁଡ୍ ଟ୍ରେଣ୍ଡ',
    emotionBreakdown: 'ଭାବନା ବିଭజନ',
    streakProgress: 'ଷ୍ଟ୍ରିକ୍ ପ୍ରଗତି',
    weeklyChallenge: 'ସାପ୍ତାହିକ ଚ୍ୟାଲେଞ୍ଜ',
    markAsComplete: 'ସମ୍ପୂର୍ଣ୍ଣ ଭାବରେ ଚିହ୍ନିତ କରନ୍ତୁ',
    completed: 'ସମ୍ପୂର୍ଣ୍ଣ!',
    goalMet: 'ଲକ୍ଷ୍ୟ ପୂରଣ ହେଲା!',
    trackADay: 'ଏକ ଦିନ ଟ୍ରାକ୍ କରନ୍ତୁ',
    days: 'ଦିନ',
    aiCallWelcomeMessage: "ନମସ୍କାର! ମୁଁ ସଂକଳ୍ପ, ଆପଣଙ୍କ ବ୍ୟକ୍ତିଗତ AI ସହାୟକ। ଆପଣ କିପରି ଅନୁଭବ କରୁଛନ୍ତି ତାହା କହି ଆପଣ କଥାବାର୍ତ୍ତା ଆରମ୍ଭ କରିପାରିବେ।",
    emotions: {
      amazed: "ଆଶ୍ଚର୍ଯ୍ୟ", amused: "ଆମୋଦିତ", angry: "କ୍ରୋଧିତ", annoyed: "ବିରକ୍ତ", anxious: "ଚିନ୍ତିତ", ashamed: "ଲଜ୍ଜିତ", brave: "ସାହସୀ", calm: "ଶାନ୍ତ", confident: "ଆତ୍ମବିଶ୍ୱାସୀ", content: "ସନ୍ତୁଷ୍ଟ", disappointed: "ନିରାଶ", discouraged: "ନିରୁତ୍ସାହିତ", disgusted: "ଘୃଣିତ", drained: "କ୍ଳାନ୍ତ", embarrassed: "ଲଜ୍ଜିତ", excited: "ଉତ୍ସାହିତ", frustrated: "ହତାଶ", grateful: "କୃତଜ୍ଞ", guilty: "ଦୋଷୀ", happy: "ଖୁସି", hopeful: "ଆଶାବାଦୀ", hopeless: "ନିରାଶ", indifferent: "ଉଦାସୀନ", irritated: "ବିରକ୍ତ", jealous: "ଈର୍ଷାପରାୟଣ", passionate: "ଭାବପ୍ରବଣ", proud: "ଗର୍ବିତ", relieved: "ଆଶ୍ୱସ୍ତ", sad: "ଦୁଃଖୀ", satisfied: "ସନ୍ତୁଷ୍ଟ",
    }
  },
  ml: {
    welcome: '{appName}ലേക്ക് സ്വാഗതം',
    appName: 'സങ്കൽപ്പം',
    description: 'വികാരങ്ങൾ മനസ്സിലാക്കാനും коледа ചെയ്യാനും ഉള്ള നിങ്ങളുടെ സ്വകാര്യ ഇടം — സുരക്ഷിതം, ലളിതം, സഹായകം.',
    ageLabel: 'ആദ്യം, നിങ്ങൾ ഏത് പ്രായവിഭാഗത്തിലാണ്?',
    ageExplainer: 'നിങ്ങളുടെ പ്രായവിഭാഗത്തിനായി ഭാഷയും ഉപദേശവും ക്രമീകരിക്കാൻ ഞങ്ങൾ ഇത് ചോദിക്കുന്നു.',
    emotionLabel: 'ഇപ്പോൾ നിങ്ങളുടെ മനസ്സിൽ എന്ത് വികാരങ്ങളാണുള്ളത്?',
    emotionCategoryUplifting: 'ഉത്തേജകമായ',
    emotionCategoryHeavy: 'ഭാരമുള്ള',
    emotionCategoryTurbulent: 'പ്രക്ഷുബ്ധമായ',
    intensityLabel: 'ഈ വികാരങ്ങൾ എത്രത്തോളം ശക്തമാണ്?',
    startButton: 'സംഭാഷണം ആരംഭിക്കുക',
    chatPlaceholder: 'നിങ്ങളുടെ സന്ദേശം ഇവിടെ ടൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ സംസാരിക്കുക...',
    dashboardTitle: 'നിങ്ങളുടെ വെൽനസ് ഡാഷ്ബോർഡ്',
    currentStreak: 'നിലവിലെ സ്ട്രീക്ക്',
    challengesDone: 'പൂർത്തിയാക്കിയ വെല്ലുവിളികൾ',
    dailyChallenge: 'ദിവസേനയുള്ള വെല്ലുവിളി',
    weeklyMoodTrend: 'പ്രതിവാര മൂഡ് ട്രെൻഡ്',
    emotionBreakdown: 'വികാരങ്ങളുടെ വിഭജനം',
    streakProgress: 'സ്ട്രീക്ക് പുരോഗതി',
    weeklyChallenge: 'പ്രതിവാര വെല്ലുവിളി',
    markAsComplete: 'പൂർത്തിയായി എന്ന് അടയാളപ്പെടുത്തുക',
    completed: 'പൂർത്തിയായി!',
    goalMet: 'ലക്ഷ്യം നേടി!',
    trackADay: 'ഒരു ദിവസം ട്രാക്ക് ചെയ്യുക',
    days: 'ദിവസങ്ങൾ',
    aiCallWelcomeMessage: "ഹലോ! ഞാൻ സങ്കൽപ്പ്, നിങ്ങളുടെ വ്യക്തിഗത AI അസിസ്റ്റന്റ് ആണ്. നിങ്ങൾക്ക് എങ്ങനെ തോന്നുന്നു എന്ന് പറഞ്ഞുകൊണ്ട് സംഭാഷണം ആരംഭിക്കാം.",
    emotions: {
      amazed: "അത്ഭുതം", amused: "വിനോദം", angry: "ദേഷ്യം", annoyed: "അസഹ്യത", anxious: "ഉത്കണ്ഠ", ashamed: "നാണം", brave: "ധൈര്യം", calm: "ശാന്തം", confident: "ആത്മവിശ്വാസം", content: "സംതൃപ്തി", disappointed: "നിരാശ", discouraged: "നിരുത്സാഹം", disgusted: "അറപ്പ്", drained: "തളർച്ച", embarrassed: "അമ്പരപ്പ്", excited: "ഉത്സാഹം", frustrated: "നിരാശ", grateful: "നന്ദി", guilty: "കുറ്റബോധം", happy: "സന്തോഷം", hopeful: "പ്രതീക്ഷ", hopeless: "നിരാശ", indifferent: "ഉദാസീനത", irritated: "പ്രകോപനം", jealous: "അസൂയ", passionate: "തീവ്രമായ", proud: "അഭിമാനം", relieved: "ആശ്വാസം", sad: "വിഷമം", satisfied: "സംതൃപ്തി",
    }
  },
  pa: {
    welcome: '{appName} ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    appName: 'ਸੰਕਲਪ',
    description: 'ਭਾਵਨਾਵਾਂ ਨੂੰ ਸਮਝਣ ਅਤੇ ਟਰੈਕ ਕਰਨ ਲਈ ਤੁਹਾਡੀ ਨਿੱਜੀ ਥਾਂ — ਸੁਰੱਖਿਅਤ, ਸਰਲ, ਸਹਾਇਕ।',
    ageLabel: 'ਪਹਿਲਾਂ, ਤੁਸੀਂ ਕਿਸ ਉਮਰ ਸਮੂਹ ਵਿੱਚ ਹੋ?',
    ageExplainer: 'ਅਸੀਂ ਇਹ ਤੁਹਾਡੇ ਉਮਰ ਸਮੂਹ ਲਈ ਭାਸ਼ਾ ਅਤੇ ਸਲਾਹ ਨੂੰ ਅਨੁਕੂਲ ਬਣਾਉਣ ਲਈ ਪੁੱਛਦੇ ਹਾਂ।',
    emotionLabel: 'ਇਸ ਵੇਲੇ ਤੁਹਾਡੇ ਅੰਦਰ ਕਿਹੜੀਆਂ ਭਾਵਨਾਵਾਂ ਮੌਜੂਦ ਹਨ?',
    emotionCategoryUplifting: 'ਉਤਸ਼ਾਹਜਨਕ',
    emotionCategoryHeavy: 'ਭਾਰੀ',
    emotionCategoryTurbulent: 'ਅਸ਼ਾਂਤ',
    intensityLabel: 'ਇਹ ਭਾਵਨਾਵਾਂ ਕਿੰਨੀਆਂ ਮਜ਼ਬੂਤ ​​ਹਨ?',
    startButton: 'ਗੱਲਬਾਤ ਸ਼ੂਰੁ ਕਰੋ',
    chatPlaceholder: 'ਆਪਣਾ ਸੁਨੇਹਾ ਇੱਥੇ ਟਾਈਪ ਕਰੋ ਜਾਂ ਬੋਲੋ...',
    dashboardTitle: 'ਤੁਹਾਡਾ ਤੰਦਰੁਸਤੀ ਡੈਸ਼ਬੋਰਡ',
    currentStreak: 'ਮੌਜੂਦਾ ਸਟ੍ਰੀਕ',
    challengesDone: 'ਪੂਰੀਆਂ ਹੋਈਆਂ ਚੁਣੌਤੀਆਂ',
    dailyChallenge: 'ਰੋਜ਼ਾਨਾ ਚੁਣੌਤੀ',
    weeklyMoodTrend: 'ਹਫ਼ਤਾਵਾਰੀ ਮੂਡ ਰੁਝਾਨ',
    emotionBreakdown: 'ਭਾਵਨਾਵਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ',
    streakProgress: 'ਸਟ੍ਰੀਕ ਤਰੱਕੀ',
    weeklyChallenge: 'ਹਫ਼ਤਾਵਾਰੀ ਚੁਣੌਤੀ',
    markAsComplete: 'ਪੂਰਾ ਹੋ ਗਿਆ ਵਜੋਂ ਮਾਰਕ ਕਰੋ',
    completed: 'ਪੂਰਾ ਹੋਇਆ!',
    goalMet: 'ਟੀਚਾ ਪੂਰਾ ਹੋਇਆ!',
    trackADay: 'ਇੱਕ ਦਿਨ ਟਰੈਕ ਕਰੋ',
    days: 'ਦਿਨ',
    aiCallWelcomeMessage: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਸੰਕਲਪ ਹਾਂ, ਤੁਹਾਡਾ ਨਿੱਜੀ AI ਸਹਾਇਕ। ਤੁਸੀਂ ਦੱਸ ਕੇ ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ ਕਿ ਤੁਸੀਂ ਕਿਵੇਂ ਮਹਿਸੂਸ ਕਰ ਰਹੇ ਹੋ।",
    emotions: {
      amazed: "ਹੈਰਾਨ", amused: "ਖੁਸ਼", angry: "ਗੁੱਸੇ", annoyed: "ਚਿੜਚਿੜਾ", anxious: "ਚਿੰਤਤ", ashamed: "ਸ਼ਰਮਿੰਦਾ", brave: "ਬਹਾਦਰ", calm: "ਸ਼ਾਂਤ", confident: "ਆਤਮ-ਵିਸ਼ਵਾਸੀ", content: "ਸੰਤੁਸ਼ਟ", disappointed: "ਨਿਰਾਸ਼", discouraged: "ਨਿਰਾਸ਼", disgusted: "ਨਫ਼ਰਤ", drained: "ਥੱਕਿਆ ਹੋਇਆ", embarrassed: "ਸ਼ਰਮਿੰਦਾ", excited: "ਉਤਸ਼ਾਹਿਤ", frustrated: "ਨਿਰਾਸ਼", grateful: "ਧੰਨਵਾਦੀ", guilty: "ਦੋਸ਼ੀ", happy: "ਖੁਸ਼", hopeful: "ਆਸਵੰਦ", hopeless: "ਨਿਰਾਸ਼", indifferent: "ਉਦਾਸੀਨ", irritated: "ਚਿੜਚିੜਾ", jealous: "ਈਰਖਾ", passionate: "ਜਨੂੰਨੀ", proud: "ਮਾਣ", relieved: "ਰਾਹਤ", sad: "ਉਦਾਸ", satisfied: "ਸੰਤੁਸ਼ਟ",
    }
  },
};